run:
  tests: false

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - exportloopref
    - goimports
    - gosec
    - nilerr
    - predeclared
    # Uncomment when this is fixed
    # https://github.com/golangci/golangci-lint/issues/1981
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

severity:
  default-severity: error
  rules:
    - linters:
        - revive
      severity: info
