run:
  tests: false
  timeout: 5m

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - bodyclose
    - exportloopref
    - goimports
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

severity:
  default-severity: error
  rules:
    - linters:
        - revive
      severity: info
