version: "2"
linters:
  enable:
    - bodyclose
    - goprintffuncname
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - whitespace
  disable:
    - errcheck
    - ineffassign
    - unused
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    rules:
      # go through patterns:
      # - exhaustive
      # - goconst
      # - godot
      # - godox
      # - gomoddirectives
      # - gosec
      # - nakedret
      # - nestif
      # - nilerr
      # - prealloc
      # - revive
      # - unconvert
      # - unparam
      # - wrapcheck
formatters:
  enable:
  - gofumpt
  - goimports
