Set Width 1600
Set Height 900
Set FontSize 22

Output soft-serve.gif
Output soft-serve-frames/

Type "ssh git.charm.sh"
Sleep 1s
Enter
Sleep 2s
Type@500ms "jjj"
Sleep 1s
Type@250ms "kkk"
Enter
Sleep 1s
Down@300ms 10
Sleep 1s
Tab@1s 2
Down@300ms 3
Enter
Down@250ms 30
Sleep 1s
Type "h"
Sleep 1s
Tab@1s 4
Sleep 500ms
Down@300ms 4
Enter
Down@300ms 2
Enter
Down
Sleep 1s
Enter
Down@250ms 50
Sleep 2.5s
Escape
Sleep 2s
