.TH SOFT 1 "2022-01-24" "soft" "A self-hostable Git server for the command line"
.SH NAME
A self-hostable Git server for the command line
.SH SYNOPSIS
\fBsoft\fP [\fIoptions\&.\&.\&.\fP] [\fIargument\&.\&.\&.\fP]
.SH DESCRIPTION
Soft Serve is a self-hostable Git server for the command line\&.
.SH OPTIONS
.TP
\fB-version\fP
display version
.SH COPYRIGHT
(C) 2021-2022 Charmbracelet, Inc\&.
.PP
Released under MIT license\&.
