name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        go-version: [~1.16]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Remove this later
    - name: Clone internal repositories
      run: |
        git clone -b release https://${{ secrets.ACCESS_TOKEN }}@github.com/charmbracelet/charm-internal ../charm
        git clone -b master https://${{ secrets.ACCESS_TOKEN }}@github.com/charmbracelet/bubbletea-internal ../bubbletea

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
